# Generated by Django 4.2.7 on 2023-12-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza_przepisow', '0002_alter_recipeingredient_measurement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='preparation_time',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
