# Generated by Django 4.2.7 on 2024-01-10 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baza_przepisow', '0003_alter_recipe_preparation_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipeingredient',
            unique_together={('recipe', 'ingredient')},
        ),
    ]
